(cl:in-package project-msg)
(cl:export '(CONNECT-VAL
          CONNECT
          LEFTX-VAL
          LEFTX
          LEFTY-VAL
          LEFTY
          RIGHTX-VAL
          RIGHTX
          RIGHTY-VAL
          RIGHTY
          LEFTTRG-VAL
          LEFTTRG
          RIGHTTRG-VAL
          RIGHTTRG
          A-VAL
          A
          B-VAL
          B
          X-VAL
          X
          Y-VAL
          Y
          PADUP-VAL
          PADUP
          PADDOWN-VAL
          PADDOWN
          PADLEFT-VAL
          PADLEFT
          PADRIGHT-VAL
          PADRIGHT
          BUMPERLEFT-VAL
          BUMPERLEFT
          BUMPERRIGHT-VAL
          BUMPERRIGHT
          GUIDE-VAL
          GUIDE
))