// Generated by gencpp from file project/deg_msg.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_DEG_MSG_H
#define PROJECT_MESSAGE_DEG_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project
{
template <class ContainerAllocator>
struct deg_msg_
{
  typedef deg_msg_<ContainerAllocator> Type;

  deg_msg_()
    : deg(0.0)  {
    }
  deg_msg_(const ContainerAllocator& _alloc)
    : deg(0.0)  {
  (void)_alloc;
    }



   typedef float _deg_type;
  _deg_type deg;





  typedef boost::shared_ptr< ::project::deg_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project::deg_msg_<ContainerAllocator> const> ConstPtr;

}; // struct deg_msg_

typedef ::project::deg_msg_<std::allocator<void> > deg_msg;

typedef boost::shared_ptr< ::project::deg_msg > deg_msgPtr;
typedef boost::shared_ptr< ::project::deg_msg const> deg_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project::deg_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project::deg_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'project': ['/home/isp/Desktop/workspace/src/project/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project::deg_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project::deg_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::deg_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::deg_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::deg_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::deg_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project::deg_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75960300fe371de17649c522b949ca85";
  }

  static const char* value(const ::project::deg_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75960300fe371de1ULL;
  static const uint64_t static_value2 = 0x7649c522b949ca85ULL;
};

template<class ContainerAllocator>
struct DataType< ::project::deg_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project/deg_msg";
  }

  static const char* value(const ::project::deg_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project::deg_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 deg\n"
;
  }

  static const char* value(const ::project::deg_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project::deg_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct deg_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project::deg_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project::deg_msg_<ContainerAllocator>& v)
  {
    s << indent << "deg: ";
    Printer<float>::stream(s, indent + "  ", v.deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_MESSAGE_DEG_MSG_H
