// Generated by gencpp from file project/motor_msg.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_MOTOR_MSG_H
#define PROJECT_MESSAGE_MOTOR_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project
{
template <class ContainerAllocator>
struct motor_msg_
{
  typedef motor_msg_<ContainerAllocator> Type;

  motor_msg_()
    : way()
    , speed(0)
    , persent(0.0)  {
    }
  motor_msg_(const ContainerAllocator& _alloc)
    : way(_alloc)
    , speed(0)
    , persent(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _way_type;
  _way_type way;

   typedef int64_t _speed_type;
  _speed_type speed;

   typedef double _persent_type;
  _persent_type persent;





  typedef boost::shared_ptr< ::project::motor_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project::motor_msg_<ContainerAllocator> const> ConstPtr;

}; // struct motor_msg_

typedef ::project::motor_msg_<std::allocator<void> > motor_msg;

typedef boost::shared_ptr< ::project::motor_msg > motor_msgPtr;
typedef boost::shared_ptr< ::project::motor_msg const> motor_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project::motor_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project::motor_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project::motor_msg_<ContainerAllocator1> & lhs, const ::project::motor_msg_<ContainerAllocator2> & rhs)
{
  return lhs.way == rhs.way &&
    lhs.speed == rhs.speed &&
    lhs.persent == rhs.persent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project::motor_msg_<ContainerAllocator1> & lhs, const ::project::motor_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::project::motor_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project::motor_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::motor_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::motor_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::motor_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::motor_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project::motor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3535bdf16ad57a8f3e9a1b542ed91b5d";
  }

  static const char* value(const ::project::motor_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3535bdf16ad57a8fULL;
  static const uint64_t static_value2 = 0x3e9a1b542ed91b5dULL;
};

template<class ContainerAllocator>
struct DataType< ::project::motor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project/motor_msg";
  }

  static const char* value(const ::project::motor_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project::motor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string way\n"
"int64 speed\n"
"float64 persent\n"
;
  }

  static const char* value(const ::project::motor_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project::motor_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.way);
      stream.next(m.speed);
      stream.next(m.persent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project::motor_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project::motor_msg_<ContainerAllocator>& v)
  {
    s << indent << "way: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.way);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
    s << indent << "persent: ";
    Printer<double>::stream(s, indent + "  ", v.persent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_MESSAGE_MOTOR_MSG_H
