// Generated by gencpp from file project/my_srv.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_MY_SRV_H
#define PROJECT_MESSAGE_MY_SRV_H

#include <ros/service_traits.h>


#include <project/my_srvRequest.h>
#include <project/my_srvResponse.h>


namespace project
{

struct my_srv
{

typedef my_srvRequest Request;
typedef my_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_srv
} // namespace project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project::my_srv > {
  static const char* value()
  {
    return "b8a2aab5099fa54e0eb1247d552c20ed";
  }

  static const char* value(const ::project::my_srv&) { return value(); }
};

template<>
struct DataType< ::project::my_srv > {
  static const char* value()
  {
    return "project/my_srv";
  }

  static const char* value(const ::project::my_srv&) { return value(); }
};


// service_traits::MD5Sum< ::project::my_srvRequest> should match
// service_traits::MD5Sum< ::project::my_srv >
template<>
struct MD5Sum< ::project::my_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project::my_srv >::value();
  }
  static const char* value(const ::project::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::my_srvRequest> should match
// service_traits::DataType< ::project::my_srv >
template<>
struct DataType< ::project::my_srvRequest>
{
  static const char* value()
  {
    return DataType< ::project::my_srv >::value();
  }
  static const char* value(const ::project::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project::my_srvResponse> should match
// service_traits::MD5Sum< ::project::my_srv >
template<>
struct MD5Sum< ::project::my_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project::my_srv >::value();
  }
  static const char* value(const ::project::my_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::my_srvResponse> should match
// service_traits::DataType< ::project::my_srv >
template<>
struct DataType< ::project::my_srvResponse>
{
  static const char* value()
  {
    return DataType< ::project::my_srv >::value();
  }
  static const char* value(const ::project::my_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_MESSAGE_MY_SRV_H
